# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title/

# Setup
title:            Seong-eun Cho
tagline:          'Cognitive Neuroscience Researcher'
description:      'M.S. Candidate in Brain & Cognitive Sciences at Seoul National University. Research interests in Spatial Cognition and Episodic Memory.'
url:              https://chosenne96.github.io
baseurl:          /

author:
  name:           'Seong-eun Cho'
  url:            https://chosenne96.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist

paginate:         5

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/chosenne96
